os: linux
language: node_js
node_js: node
before_script: npm test
script: npm run build:package
before_deploy: "cd ./dist"
deploy:
  edge: true
  provider: npm
  email: patrick@dreadful.design
  on:
    tags: true
  api_token:
    secure: VoXPtC/QNMa+nWSPx6jlekUmKD+OYMnEeceFqM5+6AS2FQ61PmVA70c5IX0Km7Fx/K8SqCYeqOq8Id5Ubn0sFXYW0HCCZ21daVxNIVfKuIBluF7l5qVYfjCwq7WcNmEmgzql3u/YP912P8/KCgW4RJ8ESvLRusk5umaTK3dttQ79nJsLUkYC5W9oAF774Ne11i/Lomo7Vv7aHVDjjRXUz2GOkJKAZJANYabhJ+7HWme+wRwH3pjiJRAbeJsH2i38hPt0Oh5SreIwnk7hlNV3DZ+rGpg6YHFO9R292U5wqX0EO0RoIsNXi8JvsvRVW6gVQ+3fFKUKo83vWayKqUJHGgCKrFGUwgGAEJoycUIvv0UzuzrZpGel1CyFdjeNdQBZ9oAtxvJHl67ksNggZUsWn0CxV1uvQvdrpyvKrq9V/jeIBlpaUbz3an6cQxCJuk/z8LsQBWq95HULFBPtvM9kUBPOYQZK6Lw5menG4GXxRSXFBZSHfCw09gWYxUKeCG0Tda79r8wJn8NPpCJ9V+fHka8M3WZcUy+/p80sqJhjBKeODDmZSJUT8v51CxtHKZA8piHhTfWlU2VRH6oDwtmuZTP3I/bbXrTLUPVBM8g+ZoTysBw+KKe4j4ZlJRZCWx4T4dLWIKeizZ2lKUnqcT4oRWs+6X2s5u/GWD46FQVhypY=
