os: linux
language: node_js
node_js: node
jobs:
  include:
    - stage: Test
      script: npm test
    - stage: Release
      if: tag =~ ^v[0-9]
      before_script: npm run build:package
      script: echo "Publishing $TRAVIS_TAG to npm..."
      before_deploy: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
      deploy:
        provider: script
        skip_cleanup: true
        script: cd ./dist && npm publish
        on:
          tags: true
          branch: master
