os: linux
language: node_js
node_js: node
script:
  - npm test
before_deploy:
  - npm run build:package
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script: cd ./dist && npm publish
  on:
    tags: true
    branch: master
