name: Run Test Suite
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 13
    - run: yarn install --frozen-lockfile
    - run: yarn lerna run build --ignore @rent_avail/docs
    - run: yarn test