name: Publish Packages

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn lerna run build --ignore @rent_avail/docs
      - run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: yarn lerna publish from-package --yes
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}