name: Publish Package

on:
  push:
    branch: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn lerna publish from-package --yes
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}